In [1]:
from DistilBERT import inference
from utilities import text_utils


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\thiba\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [2]:
sentences = [
  "You are such a bad guy",
  "I feel very good with you",
  "Yesterday I was eating breakfast",
  "There is not such thing as a miracle, you are just being foolled and being blind to it"
  ]

text = "You are such a bad guy. I feel very good with you. Yesterday I was eating breakfast. There is not such thing as a miracle, you are just being foolled and being blind to it."

text2 = "Text messages are used for personal, family, business and social purposes. Governmental and non-governmental organizations use text messaging for communication between colleagues. In the 2010s, the sending of short informal messages became an accepted part of many cultures, as happened earlier with emailing.[1] This makes texting a quick and easy way to communicate with friends, family and colleagues, including in contexts where a call would be impolite or inappropriate (e.g., calling very late at night or when one knows the other person is busy with family or work activities). Like e-mail and voicemail and unlike calls (in which the caller hopes to speak directly with the recipient), texting does not require the caller and recipient to both be free at the same moment; this permits communication even between busy individuals. Text messages can also be used to interact with automated systems, for example, to order products or services from e-commerce websites, or to participate in online contests. Advertisers and service providers use direct text marketing to send messages to mobile users about promotions, payment due dates, and other notifications instead of using postal mail, email, or voicemail."

text3 = "A sentence. A second sentence. A third sentence witout a final dot"


In [3]:
text_utils.NLTK_sentence_split(text3)

['A sentence.', 'A second sentence.', 'A third sentence witout a final dot']

In [ ]:
inference.download_BERT()

In [4]:
inference.distilbert_inference(sentences)

{'Y1': <tf.Tensor: shape=(4, 4), dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>,
 'Y2': <tf.Tensor: shape=(4, 16), dtype=float32, numpy=
 array([[1.        , 1.        , 1.        , 1.        , 1.        ,
         1.        , 1.        , 1.        , 1.        , 0.9130386 ,
         1.        , 1.        , 1.        , 0.9939713 , 1.        ,
         1.        ],
        [1.        , 1.        , 1.        , 1.        , 1.        ,
         1.        , 1.        , 1.        , 1.        , 0.9621668 ,
         1.        , 1.        , 1.        , 0.99688584, 1.        ,
         1.        ],
        [1.        , 1.        , 1.        , 1.        , 1.        ,
         1.        , 1.        , 1.        , 1.        , 0.96967745,
         1.        , 1.        , 1.        , 0.99915135, 1.        ,
         1.        ],
        [1.        , 1.        , 1.        , 1.        , 1.        ,
         1.