In [2]:
import Inference

sentences = ["You are such a bad guy","I feel very good with you","Yesterday I was eating breakfast","There is not such thing as a miracle, you are just being foolled and being blind to it"]


In [4]:
Inference.distilbert_inference(sentences)

{'Y1': <tf.Tensor: shape=(4, 4), dtype=float32, numpy=
 array([[1.       , 1.       , 0.9999267, 0.9999999],
        [1.       , 1.       , 1.       , 0.9999981],
        [1.       , 1.       , 1.       , 1.       ],
        [1.       , 1.       , 0.9999933, 1.       ]], dtype=float32)>,
 'Y2': <tf.Tensor: shape=(4, 16), dtype=float32, numpy=
 array([[0.9999968 , 0.99998856, 0.9987206 , 1.        , 0.9999994 ,
         0.989606  , 0.9999976 , 0.20016673, 0.9999951 , 0.9999331 ,
         1.        , 0.9999981 , 1.        , 0.99981457, 0.99995685,
         0.68332064],
        [1.        , 0.9999974 , 1.        , 0.99999964, 0.99797076,
         0.99997735, 0.99994516, 0.04472988, 0.9999957 , 0.99991024,
         0.9999733 , 1.        , 0.9999999 , 0.9984396 , 0.99999964,
         0.0304011 ],
        [0.9999999 , 0.9999958 , 0.9999999 , 0.99999964, 0.9999558 ,
         0.99938977, 0.99999785, 0.25262198, 0.9999995 , 0.99977225,
         0.999987  , 0.9999436 , 0.9999993 , 0.9942814 , 1.