In [1]:
import Inference

sentences = ["You are such a bad guy","I feel very good with you","Yesterday I was eating breakfast","There is not such thing as a miracle, you are just being foolled and being blind to it"]


In [2]:
Inference.distilbert_inference(sentences)

{'Y1': <tf.Tensor: shape=(4, 4), dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>,
 'Y2': <tf.Tensor: shape=(4, 16), dtype=float32, numpy=
 array([[1.        , 1.        , 1.        , 1.        , 1.        ,
         1.        , 1.        , 1.        , 1.        , 0.9130386 ,
         1.        , 1.        , 1.        , 0.9939713 , 1.        ,
         1.        ],
        [1.        , 1.        , 1.        , 1.        , 1.        ,
         1.        , 1.        , 1.        , 1.        , 0.9621668 ,
         1.        , 1.        , 1.        , 0.99688584, 1.        ,
         1.        ],
        [1.        , 1.        , 1.        , 1.        , 1.        ,
         1.        , 1.        , 1.        , 1.        , 0.96967745,
         1.        , 1.        , 1.        , 0.99915135, 1.        ,
         1.        ],
        [1.        , 1.        , 1.        , 1.        , 1.        ,
         1.